export const boardConstants = {
  GET_ALL_BOARDS_REQUEST: 'GET_ALL_BOARDS_REQUEST',
  GET_ALL_BOARDS_SUCCESS: 'GET_ALL_BOARDS_SUCCESS',
  GET_ALL_BOARDS_FAILURE: 'GET_ALL_BOARDS_FAILURE',

  GET_BOARD_REQUEST: 'GET_BOARD_REQUEST',
  GET_BOARD_SUCCESS: 'GET_BOARD_SUCCESS',
  GET_BOARD_FAILURE: 'GET_BOARD_FAILURE',

  ADD_BOARD_REQUEST: 'ADD_BOARD_REQUEST',
  ADD_BOARD_SUCCESS: 'ADD_BOARD_SUCCESS',
  ADD_BOARD_FAILURE: 'ADD_BOARD_FAILURE',

  EDIT_BOARD_REQUEST: 'EDIT_BOARD_REQUEST',
  EDIT_BOARD_SUCCESS: 'EDIT_BOARD_SUCCESS',
  EDIT_BOARD_FAILURE: 'EDIT_BOARD_FAILURE',

  DELETE_BOARD_REQUEST: 'DELETE_BOARD_REQUEST',
  DELETE_BOARD_SUCCESS: 'DELETE_BOARD_SUCCESS',
  DELETE_BOARD_FAILURE: 'DELETE_BOARD_FAILURE',

  DELETE_QUEUE_REQUEST: 'DELETE_QUEUE_REQUEST',
  DELETE_QUEUE_SUCCESS: 'DELETE_QUEUE_SUCCESS',
  DELETE_QUEUE_FAILURE: 'DELETE_QUEUE_FAILURE'
};
