export const queueConstants = {
  INIT_QUEUE: 'INIT_QUEUE',
  GET_QUEUE: 'GET_QUEUE',

  ADD_QUEUE: 'ADD_QUEUE',
  ADD_QUEUE_REQUEST: 'ADD_QUEUE_REQUEST',
  ADD_QUEUE_SUCCESS: 'ADD_QUEUE_SUCCESS',
  ADD_QUEUE_FAILURE: 'ADD_QUEUE_FAILURE',

  DELETE_QUEUE: 'DELETE_QUEUE',
  DELETE_QUEUE_REQUEST: 'DELETE_QUEUE_REQUEST',
  DELETE_QUEUE_SUCCESS: 'DELETE_QUEUE_SUCCESS',
  DELETE_QUEUE_FAILURE: 'DELETE_QUEUE_FAILURE',

  EDIT_QUEUE_REQUEST: 'EDIT_QUEUE_REQUEST',
  EDIT_QUEUE_SUCCESS: 'EDIT_QUEUE_SUCCESS',
  EDIT_QUEUE_FAILURE: 'EDIT_QUEUE_FAILURE',

  EDIT_QUEUELIST_REQUEST: 'EDIT_QUEUELIST_REQUEST',
  EDIT_QUEUELIST_SUCCESS: 'EDIT_QUEUELIST_SUCCESS',
  EDIT_QUEUELIST_FAILURE: 'EDIT_QUEUELIST_FAILURE'
};
